<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-07PEIS0" name="Default test(failed)" tests="2" failures="1" timestamp="10 Jul 2020 15:49:15 GMT" time="0.061" errors="0">
  <testcase name="test2" time="0.024" classname="demo.TestNGRetryFailedDemo"/>
  <testcase name="test3" time="0.007" classname="demo.TestNGRetryFailedDemo">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at demo.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:21)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Default test(failed) -->
